### ISSUE TITLE
[Proposal] Refactor schema to accept both required and x-example parameter in all -in (header, query param, uri param etc) parameter

### ISSUE THREAD

**Issue by singhtejpal11** [stoplightio/spectral#1455]
This refactor will help us to allow below schema:
	- name: customerId
          in: query
          description: customer id
          required: false
          type: number
          x-example: 10		  

As of now when we try with both, we are getting below exception:
Error: schema is invalid: data/required should be array
    at Ajv.validateSchema (/*/node_modules/ajv/lib/ajv.js:178:16)
    at Ajv._addSchema (/*/node_modules/ajv/lib/ajv.js:307:10)
    at Ajv.compile (/*/node_modules/ajv/lib/ajv.js:113:24)
    at WeakMap.get (/*/dist/functions/schema.js:69:29)
    at Object.exports.schema (/*/dist/functions/schema.js:89:87)
    at Object.oasExample (eval at exports.evaluateExport (/*/dist/rulesets/evaluators.js:89:80), <anonymous>:3:1163)
    at Object.exports.lintNode (/*/dist/runner/lintNode.js:30:33)
    at callback (/*/dist/runner/runner.js:38:32)
    at JSONPath._handleCallback (/*/node_modules/jsonpath-plus/dist/index-umd.js:626:7)
    at JSONPath._trace (/*/node_modules/jsonpath-plus/dist/index-umd.js:658:12)

**Comment by P0lip** [comment]
Yeah, it's a bug. Valid JSON Schema demands `required` to be an array, while we deal with `boolean` on this particular occasion.

**Comment by singhtejpal11** [comment]
Thanks for the update. Could you please confirm ,what will be the next step for this? Is it going to be fixed in new release or its already planed?

**Comment by P0lip** [comment]
> Is it going to be fixed in new release or its already planed?

It's going to be fixed, but unfortunately I cannot promise any specific date of delivery at this point.
That said, it's certainly something that'll be included in one of the next releases.
I'll keep you updated.

**Comment by singhtejpal11** [comment]
If I put x-example inside schema, it is working fine with both required and x-example parameter. Like below:
- name: customerId
  in: query
  description: customer id
  required: false
  type: number
  schema:
    x-example: 10

Also If I put type parameter inside schema and don't make any changes with required and x-example parameter, it is still working. Like below:
- name: customerId
  in: query
  description: customer id
  required: false
  schema:
    type: number
  x-example: 10

Could you please help me to understand why we need to add schema object for either type or example parameter to make it work? is there any specification change required in oas2/oas3 schema or need to make changes in validation rules?

**Comment by raleigh04** [comment]
@P0lip Did this get fixed in the latest release of Spectral?

CC: @mnaumanali94

**Comment by P0lip** [comment]
@raleigh04 unfortunately this one is not fixed. yet.
@mnaumanali94 perhaps we can get it scheduled for some upcoming sprint?
Should be a relatively easy win for us.
